language: go
branches:
    only:
        - master
go:
    - 1.4
    - 1.5
    - tip
addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-4.8
        - libsnappy-dev
        - realpath
before_install:
    - export CC="gcc-4.8"
    - mkdir deps
    - git clone https://github.com/anamariacercel/libpostalro
    - cd /libpostalro
    - ./bootstrap.sh
    - ./configure --datadir=$(pwd)/data --prefix=$(realpath $(pwd)/../deps) --bindir=$(realpath $(pwd)/../deps)
    - make install
    - cd ..
    - export PKG_CONFIG_PATH=$(pwd)/deps/lib/pkgconfig:$PKG_CONFIG_PATH
    - export LD_LIBRARY_PATH=$(pwd)/deps/lib:$LD_LIBRARY_PATH
script:
    - go test -v github.com/openvenues/gopostal/...
